# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.csbn.net:
  peer0.courier.csbn.net:
  peer0.supp1.csbn.net:
  peer0.cust1.csbn.net:

networks:
  csbn:

services:

  orderer.csbn.net:
    container_name: orderer.csbn.net
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=10150
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../organizations/ordererOrganizations/csbn.net/orderers/orderer.csbn.net/msp:/var/hyperledger/orderer/msp
        - ../organizations/ordererOrganizations/csbn.net/orderers/orderer.csbn.net/tls/:/var/hyperledger/orderer/tls
        - orderer.csbn.net:/var/hyperledger/production/orderer
    ports:
      - 10150:10150
    networks:
      - csbn

  peer0.courier.csbn.net:
    container_name: peer0.courier.csbn.net
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_csbn
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.courier.csbn.net
      - CORE_PEER_ADDRESS=peer0.courier.csbn.net:20151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:20151
      - CORE_PEER_CHAINCODEADDRESS=peer0.courier.csbn.net:20152
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:20152
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.courier.csbn.net:20151
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.courier.csbn.net:20151
      - CORE_PEER_LOCALMSPID=CourierMSP
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/courier.csbn.net/peers/peer0.courier.csbn.net/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/courier.csbn.net/peers/peer0.courier.csbn.net/tls:/etc/hyperledger/fabric/tls
        - peer0.courier.csbn.net:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 20151:20151
    networks:
      - csbn
  
  peer0.supp1.csbn.net:
    container_name: peer0.supp1.csbn.net
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_csbn
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.supp1.csbn.net
      - CORE_PEER_ADDRESS=peer0.supp1.csbn.net:30151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:30151
      - CORE_PEER_CHAINCODEADDRESS=peer0.supp1.csbn.net:30152
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:30152
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.supp1.csbn.net:30151
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.supp1.csbn.net:30151
      - CORE_PEER_LOCALMSPID=Supp1MSP
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/supp1.csbn.net/peers/peer0.supp1.csbn.net/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/supp1.csbn.net/peers/peer0.supp1.csbn.net/tls:/etc/hyperledger/fabric/tls
        - peer0.supp1.csbn.net:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 30151:30151
    networks:
      - csbn

  peer0.cust1.csbn.net:
    container_name: peer0.cust1.csbn.net
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_csbn
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.cust1.csbn.net
      - CORE_PEER_ADDRESS=peer0.cust1.csbn.net:40151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:40151
      - CORE_PEER_CHAINCODEADDRESS=peer0.cust1.csbn.net:40152
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:40152
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.cust1.csbn.net:40151
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.cust1.csbn.net:40151
      - CORE_PEER_LOCALMSPID=Cust1MSP
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/cust1.csbn.net/peers/peer0.cust1.csbn.net/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/cust1.csbn.net/peers/peer0.cust1.csbn.net/tls:/etc/hyperledger/fabric/tls
        - peer0.cust1.csbn.net:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 40151:40151
    networks:
      - csbn
  
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.supp1.csbn.net
      - peer0.courier.csbn.net
      - peer0.cust1.csbn.net
    networks:
      - csbn
